name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: VÃ©rifier les fichiers du projet
        run: |
          test -f Dockerfile
          test -f public/index.html
          test -f nginx.conf
          test -f cloudbuild.yaml
          echo "Fichiers OK"
      - name: Test index.html
        run: |
          grep -q "<h1>TP Cloud final</h1>" public/index.html
          echo "Contenu index.html OK"
